# Generated by Django 4.1.6 on 2023-02-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_item_options_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Register',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Seller_Register',
                'verbose_name_plural': 'Seller_Registers',
            },
        ),
    ]
