# Generated by Django 4.1.6 on 2023-02-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_remove_seller_register_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller_Register',
            new_name='Seller',
        ),
    ]
