# Generated by Django 4.1.6 on 2023-02-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20230212_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$LwklPlCn4fexbCTt1Rx8nh$awkDIboN3TijBchBRxT7pwW1OCS3qCFEKwruFDcImqQ=', max_length=100),
        ),
    ]
