# Generated by Django 4.1.6 on 2023-02-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_alter_seller_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$YAZRHCdLEgIaA2P5DPrZJP$faVoTCjolj2VBdbZLuRXGC3Ck62zsWc78QzS50G5fg0=', max_length=100),
        ),
    ]
