# Generated by Django 4.1.6 on 2023-02-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_alter_seller_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$XImnG9fKh7Zp8a1ELiTi1H$SryHPqTwdhPv/J+2m9m2dDiRJqUVbZeUg2DWrywcMZ8=', max_length=100),
        ),
    ]
