# Generated by Django 4.1.6 on 2023-02-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_alter_seller_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(default='pbkdf2_sha256$390000$SKqXluOmrA3KoGjUYX8rWh$qLUjI7Fo40ScSpG8EPm/x/Nhxia94WfMZCIKRwFva0k=', max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
