# Generated by Django 4.1.6 on 2023-02-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_merchant_delete_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$YlNw17lrp1YUPtGv2Gw6MR$f1s6PBTwPA2+A5FqNuoaqkGZTQqZQ5xy6vHnQvssr8k=', max_length=100),
        ),
    ]
