# Generated by Django 4.1.6 on 2023-02-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_alter_merchant_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'verbose_name': 'Merchant', 'verbose_name_plural': 'Merchants'},
        ),
        migrations.AlterField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$U34ntgLwywrrrldlkovdam$gAjSUBZAV5uw1MlPNiGEeqOKrtX/74HJwn5HWP02RD0=', max_length=100),
        ),
    ]
