# Generated by Django 4.1.6 on 2023-02-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_alter_merchant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$b0sUiUtZfX6mW8oxiW7pNw$vIrKcULThcM86wiQh7w38BtY1LU3kZesYW5E6qs2ssI=', max_length=100),
        ),
    ]
