# Generated by Django 4.1.6 on 2023-02-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_alter_merchant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$Q7dpWWVcfGXBnJ2rTzVUnb$TrGc5DexCbZaxqflNh+JAWU98be7IvTH17o/AxAuVds=', max_length=100),
        ),
    ]
