# Generated by Django 4.1.6 on 2023-02-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_alter_merchant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$D921HD5DeqlttlMyGSg71W$12uVUA48C9PZ7tVsivSIP0c8UFw34xwK3F9KAJ3YKN4=', max_length=100),
        ),
    ]
