# Generated by Django 4.1.6 on 2023-02-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0021_alter_merchant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$NcfCl6Ft2GnCNPLjHQ8S7W$1W+SKvYq028857YAzil/ENl4FIME3WRZf0WT7llFGuE=', max_length=100),
        ),
    ]
