# Generated by Django 4.1.6 on 2023-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0023_alter_merchant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$xDZL8pknkc65cAoJjGQ037$CZXenxhUVlYjP2MfiWq77wzXimkbGchjep9kUuiq9Uc=', max_length=100),
        ),
    ]
