# Generated by Django 4.1.6 on 2023-02-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exfire', '0002_customer_address_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
